### ISSUE TITLE
Carrie next steps

### ISSUE THREAD

**Issue by carrieholt** [andrew-edwards/EDMsimulate#13]
- [x] add option for vector of productivities as input to salmon_sim.R
- [x] add example in plotRealisations.Rmd of a run with time-series of productivities
- [x] add option for parallel processing, consider parLapply and foreach. From preliminary investigation, parLapply seems to improve fit more, however, should test with stan version of Larkin and Ricker (instead of mle).
- [x] add example of forecasting returns (instead of recruits) to plotRealisaztions.Rmd. If performance of EDM improves, make this the default in sim_and_fit_realisations.R
- [x] add plots of obs vs predicted values (and obs vs forecasted in last year) for an example realisation
- [x] run examples with different trends in productivity declines
- [x] check if edm outputs are aligned properly for estimation bias density plots
- [x] add violin plots to show distribution of errors for different scenarios, instead of density plots and provide some initial comparisons (R vs Rprime, constant alpha vs time-varying alpha). Any initially mentioned 'dot and line plots', perhaps from Joe's paper, but not sure what those are.
- [x] added outcome uncertainty to constant harvest rates in salmon simulation (uncertainty in the outcomes of implementing target harvest rates). This was added within sim_and_fit_realisations() to derive a variable time-series of h_t that are beta-distributed with mean and sigma as specified in that function.  This could be changed in the future to generate only a runif set of numbers in sim_and_fit_realisatoins() that are transformed into beta distribution within salmon_sim(). That way, the target harvest rate and sigma would be specified within salmon_sim() instead of sim_and_fit_realisations().
- [x] Add functions for estimating types of errors

**Comment by andrew-edwards** [comment]
- [x] regarding forth one above, `sim_and_fit_realisations()` now has `R_switch` option all set up, but not functional yet for Larkin/Ricker. Presumably your example can be used to adapt it. So we will then be able to go back and forth.
