### ISSUE TITLE
random error for recruitment deviations in salmon_sim.R and sim_and_fit_realisations.R

### ISSUE THREAD

**Issue by carrieholt** [andrew-edwards/EDMsimulate#9]
epilson_tg gives the random deviations for the age proportions so that we can keep track of the random numbers being used in in each simulation.
https://github.com/andrew-edwards/EDMsimulate/blob/a39d26a7108898a2aba5adb3ee23c2414ee4fa14/R/sim_and_fit_realisations.R#L82

However, salmon_sim also needs  a series of random numbers for the recruitment deviations (nu_t) and I don't see where these are generated in the sim_and_fit_realisations.R. Instead I think they are generated randomly within salmon_sim.R (which is the default):
https://github.com/andrew-edwards/EDMsimulate/blob/a39d26a7108898a2aba5adb3ee23c2414ee4fa14/R/salmon_sim.R#L213

**Comment by andrew-edwards** [comment]
Done in fdaef7b
